### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by realph** [firebase/vulcan#25]
I get this infinite `Loading...` message every now and again in Vulcan. I've tried logging out and logging in again but no nice.

Anyone else experiencing this issue?

**Comment by alexwolfe** [comment]
It probably has to do with the extensions you have installed in Chrome. Ad Blockers have been know to break Vulcan since they aggressively disable code even when it does not have ads. I'm looking into why this is the case, perhaps I have a variable with a certain keyword in the javascript.

**Comment by realph** [comment]
I've disabled AdBlock on that page, but I still get the constant "Loading...".

**Comment by alexwolfe** [comment]
Have you tried uninstalling and reinstalling Vulcan after uninstalling Ad
Block? Also, how large is the Firebase you are trying to access. It's
possible Vulcan may fail to load if there are more than 10,000 nodes to
display at the location you are accessing.

**Comment by mbleigh** [comment]
I'm getting the same error, no AdBlock or anything like it installed.

**Comment by alexwolfe** [comment]
@mbleigh please try uninstalling and reinstalling. Sorry about the issue. Also, verify the Firebase URL you are trying to access. If you have security rules you'll need to use your auth token to access the url in Vulcan.

**Comment by calendee** [comment]
I have similar problems.  Sometimes I see the "loading".  More often than not, I see no indication at all after clicking "Sign In".

I know my token and url are good as I can go to the console and authenticate with them.

This has actually been occurring for a very long time such that I just gave up on Vulcan.  However, I'd really like to use it.

FYI : No other extensions enabled.  Brand new download of Vulcan.  Browser closed and re-opened.

I'd say Vulcan works for me 7 out of 10 tries.

**Comment by genu** [comment]
+1 Not working for me either

**Comment by vladius** [comment]
Same here. AdBlock disabled.

**Comment by Yagger** [comment]
Same here

**Comment by elkusbry** [comment]
+1 ditto.  I have to remove the extension. close chrome.  reopen chrome and install the extension.

**Comment by Dnncha** [comment]
Infinite loading for me too, using uBlock. Tried disabling uBlock to no effect.

**Comment by jwebcat** [comment]
me too infinite loading... started yesterday

**Comment by erlandsona** [comment]
??? Infinite Loading still an issue ??? I've got it on my machine too://

**Comment by alexwolfe** [comment]
Can you uninstall and reinstall. Make sure you don't have any ad-blockers
one, for some reason they break Vulcan sometimes. Also, make sure you're
not accessing a branch that is extremely large (ie. 5000+ nodes). Hope that
helps.

**Comment by wotamann** [comment]
Every - short interruption of internet access - with open chrome & vulcane leads after reconnect to 'infinite loading' . The size of data branch doesn't matter. A Logout and new Login doesn't help. Only delete and reinstall vulcane works

**Comment by joeyyang** [comment]
Hey y'all – I'm Joey, a Firebase UX engineer.

I've pushed what I believe to be a fix to this issue (and the nonfunctional Sign In button issue) in [version 1.3.1 of Vulcan](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl?utm_source=chrome-ntp-icon). If you download the new version (please confirm by checking the version number under [chrome://extensions/](chrome://extensions/)), your data should load. 

If this is not the case, please let me know! Hopefully this makes Vulcan usable for y'all again. Thank you all!

**Comment by calendee** [comment]
Hello Joey,

I'm glad someone is making progress on this.  I have good news and bad news.

The old issue of putting in the URL and token and then .....nothing is gone.

Now, I put in the token and URL, and immediately see the login form go away and replaced with ..... "Loading".  It never goes away.

Actually, as I typed this and went to get a screenshot, it did go away and my content loaded.  Now, my computer's fan is howling at me because Chrome is running at 100%.  

I'm guessing my entire FB (about 55MB) was downloaded all at once before the view updated.

Does Vulcan really download an entire FB at once?  

FYI: I closed the window and logged in again to get the loading : 

https://www.evernote.com/shard/s246/sh/b6a4f6fa-1f9e-48bc-845f-8088bd5c0d90/7bd2c4ce09d5697fe612a1afb62190b3/deep/0/about-blank.png

**Comment by joeyyang** [comment]
Hi Justin – thanks for taking the new version for a spin! We really appreciate all the work you've done for the Firebase community. 

I'm currently investigating the "Loading..." issue, which I've reproduced locally on a much smaller node, but in answer to your question:

We load all the data under whatever URL you enter in the "Firebase URL" field through Firebase's `.on('value')` handler, and when we take the `.val()` of this, we download all the data under that node. If your Firebase is large, it'll take a while to download all that data. This is currently a limitation of Vulcan.

The dashboard on firebase.com currently has a non-realtime mode which addresses this issue for large data sets. In the meantime, it may be a better experience to use that data viewer instead. Otherwise, you can enter the URL of any child node in your Firebase to download only the data under that node. Please let me know how that works!

**Comment by joeyyang** [comment]
My previous comment wasn't accurate – we download the data when we receive the snapshot. Setting listeners on nodes where there is a lot of child data gets to be pretty expensive. We recommend storing your data as shallow and as denormalized as possible.

**Comment by realph** [comment]
@joeyyang Still having the same issue over here. I'm on 1.3.1 and it's stuck on Loading...

???

**Comment by realph** [comment]
I have to uninstall in from extensions, and then reinstall every time this happens. Is there a fix in the works?

**Comment by joeyyang** [comment]
Hi @realph — thanks for checking back in! I'm working on some fixes at the moment that I hope to have out soon. Thanks!
